{{- if .Values.configmap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := .Values.configmap }}
  {{ $key }}: {{ include "interop-eks-cronjob-chart.render-template" (dict "value" $val "context" $) | quote }} 
  {{- end }}
{{- end }}
