apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "interop-eks-cronjob-chart.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ include "interop-eks-cronjob-chart.render-template" (dict "value" .Values.serviceAccount.roleArn "context" $) }}
  {{- end }}