apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "interop-eks-cronjob-chart.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ include "interop-eks-cronjob-chart.render-template" (dict "value" (default "" .Values.serviceAccount.roleArn) "context" $) }}
