# Default values for interop-eks-cronjob-chart.

# -- Name of the service that will be deployed on K8s cluster
name:
# -- Namespace hosting the service that will be deployed on K8s cluster
namespace:
# -- (int) Number of desired replicas for the service being deployed
# @default -- 1
replicas: 
# -- (string) ServiceAccount roleARN used for eks.amazonaws.com/role-arn annotation
roleArn:
# -- (enum) Defines the technology used to develop the container. The following values are allowed: [ "nodejs", "scala"]
techStack: 

# -- [failedJobsHistoryLimit](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#jobs-history-limits) field specifies the number of failed finished jobs to keep. Setting this field to 0 will not keep any failed jobs.
# @default -- 1
failedJobsHistoryLimit: 1
# -- [successfulJobsHistoryLimit](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#jobs-history-limits) field specifies the number of successful finished jobs to keep. Setting this field to 0 will not keep any successful jobs
# @default -- 0
successfulJobsHistoryLimit: 0
# -- (boolean) [suspend](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#schedule-suspension) field allows to suspend execution of Jobs for a CronJob. 
# @default -- false.
suspend: false
# -- (int) The activeDeadlineSeconds applies to the duration of the job, no matter how many Pods are created. Once a Job reaches activeDeadlineSeconds, all of its running Pods are terminated.
# @default -- 3600
activeDeadlineSeconds: 3600
# -- (string) The [schedule](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#schedule-syntax) field is required. The value of that field follows the [Cron](https://en.wikipedia.org/wiki/Cron) syntax.
schedule: 
# -- (string) [concurrencyPolicy](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#concurrency-policy) field specifies how to treat concurrent executions of a Job that is created by this CronJob.
# @default -- Allow
concurrencyPolicy: 
restartPolicy: OnFailure

image:
  imagePullPolicy: Always
  # -- (string) Image repository
  repositoryPrefix:
  # -- (string) Image tag
  tag:
  # -- (string) Image digest
  digest:

# -- K8s container resources requests and limits
resources:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory:

